# Creating a basic ingest of a NetCDF file

In [1]:
### Sometimes a file might be in the netCDF file format but not conform to cfradial standards and can't
### be read with Py-ART. One way of working around this is to create a basic ingest, here is a hypothetically
### example, this file can be read with Py-ART, but lets act like it doesn't! :)

In [1]:
import netCDF4
import pyart
import numpy as np


## You are using the Python ARM Radar Toolkit (Py-ART), an open source
## library for working with weather radar data. Py-ART is partly
## supported by the U.S. Department of Energy as part of the Atmospheric
## Radiation Measurement (ARM) Climate Research Facility, an Office of
## Science user facility.
##
## If you use this software to prepare a publication, please cite:
##
##     JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119



/home/spol/anaconda3/lib/python3.9/site-packages/xarray/core/pycompat.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion(duck_array_module.__version__)
/home/spol/anaconda3/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/spol/anaconda3/lib/python3.9/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")
/home/spol/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
/home/spol/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Versio

In [3]:
# We will read the nc data with netCDF4.Dataset

In [2]:
data = netCDF4.Dataset("/home/spol/git/pyart/doc/source/notebooks/test_radar_0.nc")

In [3]:
# Lets get an idea of the shapes for rays and gates and the keys in this dataset.

In [4]:
data.variables.keys()

dict_keys(['volume_number', 'platform_type', 'primary_axis', 'status_xml', 'instrument_type', 'radar_antenna_gain_h', 'radar_antenna_gain_v', 'radar_beam_width_h', 'radar_beam_width_v', 'radar_rx_bandwidth', 'time_coverage_start', 'time_coverage_end', 'frequency', 'grid_mapping', 'latitude', 'longitude', 'altitude', 'altitude_agl', 'sweep_number', 'sweep_mode', 'polarization_mode', 'prt_mode', 'follow_mode', 'fixed_angle', 'target_scan_rate', 'sweep_start_ray_index', 'sweep_end_ray_index', 'rays_are_indexed', 'ray_angle_res', 'r_calib_time', 'r_calib_pulse_width', 'r_calib_xmit_power_h', 'r_calib_xmit_power_v', 'r_calib_two_way_waveguide_loss_h', 'r_calib_two_way_waveguide_loss_v', 'r_calib_two_way_radome_loss_h', 'r_calib_two_way_radome_loss_v', 'r_calib_receiver_mismatch_loss', 'r_calib_k_squared_water', 'r_calib_radar_constant_h', 'r_calib_radar_constant_v', 'r_calib_antenna_gain_h', 'r_calib_antenna_gain_v', 'r_calib_noise_hc', 'r_calib_noise_vc', 'r_calib_noise_hx', 'r_calib_noise

In [5]:
data['azimuth'][:].shape

(480,)

In [6]:
data['range'][:].shape

(1593,)

In [7]:
# Make a empty radar with the dimensions of the dataset.

In [8]:
radar = pyart.testing.make_empty_ppi_radar(667, 400, 1)

In [9]:
# Start filling the radar attributes with variables in the dataset.

In [10]:
radar.time['data'] = np.array(data['time'][:])

In [11]:
data['longitude'][:]

masked_array(data=120.90746307,
             mask=False,
       fill_value=1e+20)

In [12]:
radar.latitude['data'] = np.array([data['latitude'][:]])

In [13]:
radar.longitude['data'] = np.array([data['longitude'][:]])

In [14]:
radar.longitude['data']

array([120.90746307])

In [15]:
radar.range['data'] = np.array(data['range'][:])

In [16]:
# Sometimes the dataset might just contain gate spacing, but if the gate spacing is uniform,
# there is a way around it, we see a gate spacing of 60 above.

In [17]:
radar.range['data'] = np.linspace(0.0, 60.0*(667-1), 667)

In [18]:
# As you can see below we obtained the same range data. This isn't needed
# if the range data is present, but using gate spacing and ngates is another way around it../output/20220531/cfrad.20220531_084850.258_to_20220531_084924.470_SPOL_SUR.nc

In [19]:
radar.range['data']

array([    0.,    60.,   120.,   180.,   240.,   300.,   360.,   420.,
         480.,   540.,   600.,   660.,   720.,   780.,   840.,   900.,
         960.,  1020.,  1080.,  1140.,  1200.,  1260.,  1320.,  1380.,
        1440.,  1500.,  1560.,  1620.,  1680.,  1740.,  1800.,  1860.,
        1920.,  1980.,  2040.,  2100.,  2160.,  2220.,  2280.,  2340.,
        2400.,  2460.,  2520.,  2580.,  2640.,  2700.,  2760.,  2820.,
        2880.,  2940.,  3000.,  3060.,  3120.,  3180.,  3240.,  3300.,
        3360.,  3420.,  3480.,  3540.,  3600.,  3660.,  3720.,  3780.,
        3840.,  3900.,  3960.,  4020.,  4080.,  4140.,  4200.,  4260.,
        4320.,  4380.,  4440.,  4500.,  4560.,  4620.,  4680.,  4740.,
        4800.,  4860.,  4920.,  4980.,  5040.,  5100.,  5160.,  5220.,
        5280.,  5340.,  5400.,  5460.,  5520.,  5580.,  5640.,  5700.,
        5760.,  5820.,  5880.,  5940.,  6000.,  6060.,  6120.,  6180.,
        6240.,  6300.,  6360.,  6420.,  6480.,  6540.,  6600.,  6660.,
      

In [20]:
radar.fixed_angle['data'] = np.array(data['fixed_angle'])

In [21]:
radar.sweep_number['data'] = np.array(data['sweep_number'])

In [22]:
radar.sweep_start_ray_index['data'] = np.array(data['sweep_start_ray_index'])

In [23]:
radar.sweep_end_ray_index['data'] = np.array(data['sweep_end_ray_index'])

In [24]:
radar.altitude['data'] = np.array(data['altitude'])

In [36]:
radar.azimuth['data'] = np.array(data['azimuth'])

In [37]:
radar.sweep_mode['data'] = np.array(data['sweep_mode'])

In [38]:
data['fixed_angle'][:]

masked_array(data=[0.50413513],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [39]:
# If elevation doesn't exist, but fixed angle doesn't, you can do
# fixed angle multiplied by nrays

In [40]:
radar.elevation['data'] = np.array([data['fixed_angle'][:]]*len(data['azimuth'][:])).squeeze()

In [41]:
# With elevation and azimuth in the radar object, lets recalculate
# gate latitude, longitude and altitude,

In [42]:
radar.init_gate_altitude()
radar.init_gate_longitude_latitude()

In [43]:
radar.gate_longitude['data']

array([[120.90746307, 120.9069299 , 120.90639672, ..., 120.5530001 ,
        120.55246562, 120.55193113],
       [120.90746307, 120.90693339, 120.9064037 , ..., 120.55530659,
        120.55477557, 120.55424454],
       [120.90746307, 120.90693697, 120.90641086, ..., 120.55767365,
        120.55714618, 120.5566187 ],
       ...,
       [120.90746307, 120.90691999, 120.9063769 , ..., 120.54644809,
        120.54590379, 120.54535948],
       [120.90746307, 120.9069232 , 120.90638332, ..., 120.54857047,
        120.54802934, 120.54748822],
       [120.90746307, 120.9069265 , 120.90638993, ..., 120.55075457,
        120.55021672, 120.54967887]])

In [44]:
# Let's work on the field data, we will just do reflectivity for now, but any of the
# other fields can be done the same way and added as a key pair in the fields dict.

In [45]:
from pyart.config import get_metadata

In [46]:
ref_dict = get_metadata('DBZ')

In [47]:
ref_dict['data'] = np.array(data['DBZ'])

In [48]:
ref_dict['data']

array([[ -1.3892136,   3.5708647,   5.9396906, ...,  13.02022  ,
         16.219433 ,  14.870054 ],
       [ -6.4790382,  10.619883 ,   7.539297 , ...,  15.079504 ,
         14.010011 ,  11.739422 ],
       [ -4.169525 ,  19.020134 ,  12.831158 , ...,  13.700469 ,
         15.420556 ,  37.709393 ],
       ...,
       [ -6.201008 ,  21.249945 ,  12.91086  , ...,   0.6589508,
          4.530999 ,   2.469861 ],
       [ -7.969286 ,  14.149026 ,   9.700526 , ...,  14.210194 ,
         15.770875 ,  37.709393 ],
       [-11.129574 ,  -1.5412025,   4.1102448, ...,  17.670755 ,
         19.220316 ,  15.179595 ]], dtype=float32)

In [49]:
radar.fields = {'DBZ': ref_dict}

In [50]:
radar

In [51]:
# Now what does that data look like plotted with Py-ART, also confirm if it works.

In [52]:
import matplotlib.pyplot as plt

In [75]:
display = pyart.graph.RadarMapDisplay(radar)

/home/spol/anaconda3/lib/python3.9/site-packages/cartopy/crs.py:2320: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.float(self.globe.semimajor_axis or WGS84_SEMIMAJOR_AXIS)
/home/spol/anaconda3/lib/python3.9/site-packages/cartopy/crs.py:2321: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.float(self.globe.semiminor_axis or a)

In [53]:
display.plot_ppi('DBZ')
plt.show()

AttributeError: 'function' object has no attribute 'plot_ppi'